//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.22 at 12:02:54 PM CEST 
//


package ai.aitia.meme.paramsweep.settingsxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for block_element complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="block_element">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" type="{}blockElementTypes" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "block_element")
@XmlSeeAlso({
    BlockElementComplex.class,
    BlockElementText.class
})
public class BlockElement {

    @XmlAttribute(name = "type")
    protected BlockElementTypes blockElementType;

    /**
     * Gets the value of the blockElementType property.
     * 
     * @return
     *     possible object is
     *     {@link BlockElementTypes }
     *     
     */
    public BlockElementTypes getBlockElementType() {
        return blockElementType;
    }

    /**
     * Sets the value of the blockElementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlockElementTypes }
     *     
     */
    public void setBlockElementType(BlockElementTypes value) {
        this.blockElementType = value;
    }

}
