//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.17 at 02:52:01 PM CET 
//


package ai.aitia.meme.paramsweep.settingsxml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ai.aitia.meme.paramsweep.settingsxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BlockElement_QNAME = new QName("", "block_element");
    private final static QName _BlockElementCpx_QNAME = new QName("", "block_element_cpx");
    private final static QName _BlockElementStr_QNAME = new QName("", "block_element_str");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ai.aitia.meme.paramsweep.settingsxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BlockElement }
     * 
     */
    public BlockElement createBlockElement() {
        return new BlockElement();
    }

    /**
     * Create an instance of {@link RecordersPage }
     * 
     */
    public RecordersPage createRecordersPage() {
        return new RecordersPage();
    }

    /**
     * Create an instance of {@link StopData }
     * 
     */
    public StopData createStopData() {
        return new StopData();
    }

    /**
     * Create an instance of {@link Scripts }
     * 
     */
    public Scripts createScripts() {
        return new Scripts();
    }

    /**
     * Create an instance of {@link Recorders }
     * 
     */
    public Recorders createRecorders() {
        return new Recorders();
    }

    /**
     * Create an instance of {@link BlockElementComplex }
     * 
     */
    public BlockElementComplex createBlockElementComplex() {
        return new BlockElementComplex();
    }

    /**
     * Create an instance of {@link BlockElementText }
     * 
     */
    public BlockElementText createBlockElementText() {
        return new BlockElementText();
    }

    /**
     * Create an instance of {@link Member }
     * 
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link WritingTime }
     * 
     */
    public WritingTime createWritingTime() {
        return new WritingTime();
    }

    /**
     * Create an instance of {@link BuildBlocks }
     * 
     */
    public BuildBlocks createBuildBlocks() {
        return new BuildBlocks();
    }

    /**
     * Create an instance of {@link Parent }
     * 
     */
    public Parent createParent() {
        return new Parent();
    }

    /**
     * Create an instance of {@link Block }
     * 
     */
    public Block createBlock() {
        return new Block();
    }

    /**
     * Create an instance of {@link Script }
     * 
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link Recorder }
     * 
     */
    public Recorder createRecorder() {
        return new Recorder();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "block_element")
    public JAXBElement<BlockElement> createBlockElement(BlockElement value) {
        return new JAXBElement<BlockElement>(_BlockElement_QNAME, BlockElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockElementComplex }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "block_element_cpx", substitutionHeadNamespace = "", substitutionHeadName = "block_element")
    public JAXBElement<BlockElementComplex> createBlockElementCpx(BlockElementComplex value) {
        return new JAXBElement<BlockElementComplex>(_BlockElementCpx_QNAME, BlockElementComplex.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockElementText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "block_element_str", substitutionHeadNamespace = "", substitutionHeadName = "block_element")
    public JAXBElement<BlockElementText> createBlockElementStr(BlockElementText value) {
        return new JAXBElement<BlockElementText>(_BlockElementStr_QNAME, BlockElementText.class, null, value);
    }

}
