//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.17 at 02:52:01 PM CET 
//


package ai.aitia.meme.paramsweep.settingsxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stop_data" type="{}stop_data"/>
 *         &lt;element name="user_variables" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scripts" type="{}scripts"/>
 *         &lt;element name="recorders" type="{}recorders"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stopData",
    "userVariables",
    "scripts",
    "recorders"
})
@XmlRootElement(name = "recorders_page")
public class RecordersPage {

    @XmlElement(name = "stop_data", required = true)
    protected StopData stopData;
    @XmlElement(name = "user_variables", required = true)
    protected String userVariables;
    @XmlElement(required = true)
    protected Scripts scripts;
    @XmlElement(required = true)
    protected Recorders recorders;

    /**
     * Gets the value of the stopData property.
     * 
     * @return
     *     possible object is
     *     {@link StopData }
     *     
     */
    public StopData getStopData() {
        return stopData;
    }

    /**
     * Sets the value of the stopData property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopData }
     *     
     */
    public void setStopData(StopData value) {
        this.stopData = value;
    }

    /**
     * Gets the value of the userVariables property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserVariables() {
        return userVariables;
    }

    /**
     * Sets the value of the userVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserVariables(String value) {
        this.userVariables = value;
    }

    /**
     * Gets the value of the scripts property.
     * 
     * @return
     *     possible object is
     *     {@link Scripts }
     *     
     */
    public Scripts getScripts() {
        return scripts;
    }

    /**
     * Sets the value of the scripts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scripts }
     *     
     */
    public void setScripts(Scripts value) {
        this.scripts = value;
    }

    /**
     * Gets the value of the recorders property.
     * 
     * @return
     *     possible object is
     *     {@link Recorders }
     *     
     */
    public Recorders getRecorders() {
        return recorders;
    }

    /**
     * Sets the value of the recorders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recorders }
     *     
     */
    public void setRecorders(Recorders value) {
        this.recorders = value;
    }

}
