//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.17 at 02:52:01 PM CET 
//


package ai.aitia.meme.paramsweep.settingsxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scriptTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="scriptTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="stat"/>
 *     &lt;enumeration value="operator"/>
 *     &lt;enumeration value="script"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "scriptTypes")
@XmlEnum
public enum ScriptTypes {

    @XmlEnumValue("stat")
    STAT("stat"),
    @XmlEnumValue("operator")
    OPERATOR("operator"),
    @XmlEnumValue("script")
    SCRIPT("script");
    private final String value;

    ScriptTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScriptTypes fromValue(String v) {
        for (ScriptTypes c: ScriptTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
